branches: ['master']
ci: true
debug: true
dryRun: false
tagFormat: 'v${version}'

# Global plugin options (will be passed to all plugins)
preset: 'conventionalcommits'
gitlabUrl: 'https://hr-tm-cms-git.cisco.com/collaboration_device_macros/ciscodevice_homekit_bridge/' # your gitlab url

# Responsible for verifying conditions necessary to proceed with the release:
# configuration is correct, authentication token are valid, etc...
verifyConditions:
  - '@semantic-release/changelog'
  - '@semantic-release/git'
  - '@semantic-release/gitlab'
  - '@eclass/semantic-release-sentry-releases'

# Responsible for determining the type of the next release (major, minor or patch).
# If multiple plugins with a analyzeCommits step are defined, the release type will be
# the highest one among plugins output.
# Look details at: https://github.com/semantic-release/commit-analyzer#configuration
analyzeCommits:
  - path: '@semantic-release/commit-analyzer'

# Responsible for generating the content of the release note.
# If multiple plugins with a generateNotes step are defined,
# the release notes will be the result of the concatenation of each plugin output.
generateNotes:
  - path: '@semantic-release/release-notes-generator'
    writerOpts:
      groupBy: 'type'
      commitGroupsSort: 'title'
      commitsSort: 'header'
    linkCompare: true
    linkReferences: true

# Responsible for preparing the release, for example creating or updating files
# such as package.json, CHANGELOG.md, documentation or compiled assets
# and pushing a commit.
prepare:
  - path: '@semantic-release/changelog'
  - path: '@semantic-release/npm'
  - path: '@semantic-release/git'
    message: 'RELEASE: ${nextRelease.version} [skip ci]'
    assets: ['CHANGELOG.md', 'package.json']

# Responsible for publishing the release.
publish:
  - path: '@semantic-release/gitlab'
# TODO: The semantic-release-sentry-releases tool is currently throwing an error when publishing to sentry, bug is being fixed by their team.
# TODO: In the mean time we can manually upload sentry via deploy.sh file.
#  - path: '@eclass/semantic-release-sentry-releases'

success: false
# - path: 'semantic-release-slack-bot'
#   notifyOnSuccess: true
#   markdownReleaseNotes: false

fail: false
# - path: 'semantic-release-slack-bot'
#   notifyOnFail: true

